rd /S /Q "var\cache\test"
rd /S /Q "var\cache\test_old"
rd /S /Q "var\cache\prod"
rd /S /Q "var\cache\prod_old"
rd /S /Q "var\cache\dev"
rd /S /Q "var\cache\dev_old"
del /Q   "var\logs\dev.log"
del /Q   "var\logs\test.log"
del /Q   "var\logs\prod.log"
