<?php

namespace SmartCore\Bundle\FelibBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LibraryPathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryPathRepository extends EntityRepository
{
}
