<?php

namespace SmartCore\Bundle\FelibBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LibraryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryRepository extends EntityRepository
{
}
